modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "muffins_api_test"
version = "1.0"
displayName = "Muffin's API Test"
authors = "FireMuffin303"
description = '''

'''
#logoFile = ""

[[dependencies.muffins_api_test]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.muffins_api_test]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"