modLoader = "javafml"
loaderVersion = "[2,)"
license = "GPL-3.0"

[[mods]]
modId = "muffins_ovenapi"
version = "${version}"
displayName = "Muffin's Oven API"
authors = "FireMuffin303"
description = '''
A library mod for FireMuffin303's Mods.
'''
logoFile = "icon.png"

[[dependencies.muffins_ovenapi]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.muffins_ovenapi]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "muffinsmcapi.mixins.json"

[[mixins]]
config = "muffinsmcapi.neoforge.mixins.json"
